### ISSUE TITLE
Intergration with various plugins broken

### ISSUE THREAD

**Issue by sallreds** [magnusulf/Factions#65]
## Affected Plugin

- **Affected Plugin Name:** FactionsDynmap, DefensiveTurrets
- **Affected Plugin Version:** Latest/All

## Describe your Environment

- **Server Version:** 1.14.4 Spigot (NOT Paper)

## Steps to Reproduce this Bug

1. Install Factions3 + MassiveCore
2. Install the affected plugins (FactionsDynmap, DefensiveTurrets)
3. Bug will be reproduced

## Observed Results

No errors I think, but any integration with these plugins doesn't exist. FactionsDynmap cant find massive core though, so maybe it's something to do with you changing the version or name of the plugin?
## Expected Results

Expected was that FD and DT would intergrate with factions for showing on dynmap and turret teams, but that didn't happen.

**Comment by magnusulf** [comment]
FactionsDynmap was maintained by the MassiveCraft Development team when they stopped updating Factions they also stopped updating that. Unfortunately it is a closed source project so I can't do anything to update it and would have to make my own version from scratch (which I might do).

I can't say anything specific about DefensiveTurrents. I had to change the Factions API in order to move the plugin forward so they are probably still using the old API. I can't do much about that.
